### PR TITLE
Fix setNullValues and add support for timestamp arrow type

### PR DESCRIPTION
**Pull request by fexolm**

### CODE REVIEW

**Comment by Garra1980** [comment]
What about some test that checks import?

**Comment by anton-malakhov** [comment]
why "modin" branch? @Garra1980 what branch should we use?

**Comment by fexolm** [comment]
@Garra1980 as far as I know we don't have db engine tests right now. ArrowCsvFSI already has tests for that. I will add tests for ArrowFSI as far as we have some db engine tests.

**Comment by fexolm** [comment]
@anton-malakhov I've changed the base branch, it looks like it does not rebase properly. I would fix that as soon, as  I get results for out benchmarks.

**Comment by fexolm** [comment]
@anton-malakhov I fixed the branch. TY

**Pull request merged**
